import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../database/identity_repository.dart';
import '../models/identity.dart';
import '../services/encryption_service.dart';

final identityRepositoryProvider = Provider<IdentityRepository>((ref) => IdentityRepository());

final identityProvider = AsyncNotifierProvider<IdentityNotifier, Identity?>(
  IdentityNotifier.new,
);

class IdentityNotifier extends AsyncNotifier<Identity?> {
  @override
  Future<Identity?> build() async {
    final repo = ref.read(identityRepositoryProvider);
    return repo.getIdentity();
  }

  /// Splash screen calls this to decide whether to route to Create
  /// Profile (first launch) or straight to Home.
  Future<bool> hasIdentity() async {
    final current = await future;
    return current != null;
  }

  /// Generates a brand-new X25519 keypair and persists it under the
  /// given [lettalkId]. The ID itself is generated by the caller (the
  /// Create Profile screen) so the user can see it on screen *before*
  /// confirming, and what they saw is exactly what gets saved.
  Future<Identity> createIdentity(String username, {required String lettalkId}) async {
    final encryption = EncryptionService.instance;
    final keyPair = await encryption.generateKeyPair();
    final encryptedPrivateKey = await encryption.encryptPrivateKey(keyPair.privateKeyPlain);

    final identity = Identity(
      lettalkId: lettalkId,
      username: username.trim().isEmpty ? 'Anonymous' : username.trim(),
      encryptedPrivateKey: encryptedPrivateKey,
      publicKey: keyPair.publicKey,
      createdAt: DateTime.now().millisecondsSinceEpoch,
    );

    final repo = ref.read(identityRepositoryProvider);
    await repo.saveIdentity(identity);
    state = AsyncData(identity);
    return identity;
  }

  Future<void> updateUsername(String username) async {
    final repo = ref.read(identityRepositoryProvider);
    await repo.updateUsername(username);
    final current = state.value;
    if (current != null) {
      state = AsyncData(current.copyWith(username: username));
    }
  }

  Future<void> logout() async {
    final repo = ref.read(identityRepositoryProvider);
    await repo.clearIdentity();
    state = const AsyncData(null);
  }
}
